### ISSUE TITLE
(Device Event) Error msg occurs when deconnecting UsbAccessory.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#76]
**Describe the bug**

I usually use a navigation or music app in my car by connecting my phone to the car.
After I drove a car, I disconnected my smartphone as usual.
At the time, this error msg occurred.

**To Reproduce**
1. Connect the phone to the car and run the Android Auto app.
2. Disconnect the phone
3. Error msg occurs in any seconds.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/8052474/96967938-2c9ab900-154b-11eb-93ed-295a8852f8c3.png)

**Smartphone (please complete the following information):**
 - Device: Note 9
 - OS: Android 10
 - Version: 0.9.9-beta and 0.9.9-gamma

**Additional context**

**Comment by woohyeok-choi** [comment]
This error occurs because the app does not have any permission for accessing to a given USB device or accessory. 
In the current implementation, USB's detached event is collected (attached event cannot be collected).
However, to receive this event, the app should be granted by a user with a special permission dialog.

In the next version, I'm gonna remove this event due to:
1) Cannot gather attached event; I think that data analysis related to USB using only detach events has no meaning.
2) Too burdensome to get permission for each USB devices.
